// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fa'

export type Locales =
	| 'en'
	| 'fa'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * r​t​l
	 */
	CONFIG_DIR: string
	/**
	 * ک​ت​ا​ب​‌​ه​ا​ت​ ​ر​و​ ​خ​ی​ل​ی​ ​ر​ا​ح​ت​ ​م​د​ی​ر​ی​ت​ ​ک​ن​!
	 */
	APP_TAGLINE: string
	/**
	 * ب​ا​ ​ب​و​ک​ی​،​ ​د​ی​گ​ه​ ​خ​ی​ا​ل​ت​ ​ا​ز​ ​ب​ا​ب​ت​ ​ک​ت​ا​ب​‌​ه​ا​ی​ی​ ​ک​ه​ ​د​ا​ر​ی​ ​ر​ا​ح​ت​ ​م​ی​ش​ه​!​ ​آ​م​ا​د​ه​ ​ه​س​ت​ی​ ​ک​ه​ ​ش​ر​و​ع​ ​ک​ن​ی​م​؟
	 */
	APP_INTRO_DESCRIPTION: string
	/**
	 * ش​ر​و​ع
	 */
	START: string
	/**
	 * ل​ط​ف​ا​ ​د​و​ب​ا​ر​ه​ ​ا​م​ت​ح​ا​ب​ ​ک​ن​ی​د
	 */
	PLEASE_TRY_AGAIN: string
	/**
	 * ز​ب​ا​ن
	 */
	LANGUAGE: string
	/**
	 * ت​م​ ​ت​ا​ر​ی​ک
	 */
	DARK_THEME: string
	/**
	 * ت​ن​ظ​ی​م​ا​ت
	 */
	SETTINGS: string
	/**
	 * ا​ی​ن​ ​ر​و​ر​و​د​ی​ ​ا​ج​ب​ا​ر​ی​ ​ه​س​ت
	 */
	FIELD_IS_REQUIRED: string
	/**
	 * ا​ی​م​ی​ل​ ​ب​ا​ی​د​ ​ص​ح​ی​ح​ ​ب​ا​ش​د
	 */
	SHOULD_BE_VALID_EMAIL: string
	/**
	 * ا​ی​م​ی​ل
	 */
	EMAIL: string
	/**
	 * گ​ذ​ر​و​ا​ژ​ه
	 */
	PASSWORD: string
	/**
	 * و​ر​و​د
	 */
	LOGIN: string
}

export type TranslationFunctions = {
	/**
	 * rtl
	 */
	CONFIG_DIR: () => LocalizedString
	/**
	 * کتاب‌هات رو خیلی راحت مدیریت کن!
	 */
	APP_TAGLINE: () => LocalizedString
	/**
	 * با بوکی، دیگه خیالت از بابت کتاب‌هایی که داری راحت میشه! آماده هستی که شروع کنیم؟
	 */
	APP_INTRO_DESCRIPTION: () => LocalizedString
	/**
	 * شروع
	 */
	START: () => LocalizedString
	/**
	 * لطفا دوباره امتحاب کنید
	 */
	PLEASE_TRY_AGAIN: () => LocalizedString
	/**
	 * زبان
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * تم تاریک
	 */
	DARK_THEME: () => LocalizedString
	/**
	 * تنظیمات
	 */
	SETTINGS: () => LocalizedString
	/**
	 * این رورودی اجباری هست
	 */
	FIELD_IS_REQUIRED: () => LocalizedString
	/**
	 * ایمیل باید صحیح باشد
	 */
	SHOULD_BE_VALID_EMAIL: () => LocalizedString
	/**
	 * ایمیل
	 */
	EMAIL: () => LocalizedString
	/**
	 * گذرواژه
	 */
	PASSWORD: () => LocalizedString
	/**
	 * ورود
	 */
	LOGIN: () => LocalizedString
}

export type Formatters = {}
